name: First Workflow

# allows us to manually start the workflow
on: workflow_dispatch
jobs:
  first-job:
    # can search for git 
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: Print Goodbye
        run: echo "Done - bye!"


